# FLP Project 2 (Prolog) - Skeleton of a graph
# Author: Michal Pysik (xpysik00)

all:
	swipl -q -g solve -o flp22-log -c input2.pl graph_skeleton.pl

zip:
	zip -r flp-log-xpysik00.zip *.pl Makefile tests README

clean:
	rm -f flp22-log flp-log-xpysik00.zip
