# Project: FLP Project 1 - Functional Knapsack problem solution in Haskell
# Author: Michal Pysik (login: xpysik00)
# Year: 2023

all:
	ghc src/*.hs -o flp22-fun -Wall

clean:
	rm -f src/*.o src/*.hi flp22-fun
